#
# Blog Settings
#
author: Denis Gladkikh
description: Denis Gladkikh (outcoldman) - Personal blog about software development 
url: http://outcoldman.com
title: Denis Gladkikh (outcoldman) - Personal blog about software development 

#
# Jekyll Settings
#
markdown: redcarpet
pygments: true
permalink: /:categories/archive/:year/:month/:day/:title/
safe: false
exclude: [bower_components, node_modules]

# Disqus Comments
disqus_short_name: outcoldman
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-7023371-5