#
# Blog Settings
#
author: Denis Gladkikh
description: Blog about software development 
url: http://outcoldman.com
title: Blog about software development 

#
# Jekyll Settings
#
markdown: redcarpet
pygments: true
permalink: /:categories/archive/:year/:month/:day/:title/
safe: false
exclude: [bower_components, node_modules]

# Disqus Comments
disqus_short_name: outcoldman
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-7023371-5

# Github repositories
github_user: outcoldman
github_repo_url: https://github.com/outcoldman/outcoldman.com/